#!/usr/bin/env python3

import socket
import select
import sys
from os import environ
from os.path import join, dirname, realpath
from time import sleep

from dotenv import load_dotenv

projectRoot = realpath(dirname(__file__) + '/..')

dotenv_path = join(projectRoot, '.env')
load_dotenv(dotenv_path)

ipAddress = environ.get('IP_ADDRESS')
port = environ.get('PORT')

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.connect((ipAddress, int(port)))

while True:
    socketsList = [sys.stdin, server]

    readSockets, writeSocket, errorSocket = select.select(socketsList, [], [])

    for socks in readSockets:
        if socks == server:
            message = socks.recv(2048).decode('utf-8')
            print(message)
        else:
            message = sys.stdin.readline()
            server.sendall(message.encode('utf-8'))
            print(f'<You>: {message}')
            sys.stdout.flush()
    sleep(1)
